#!/bin/sh
[ -f /etc/profile.d/RkEnv.sh ] && source /etc/profile.d/RkEnv.sh
case $1 in
# DISABLING with '_m' suffix
start)
	sh /oem/usr/bin/RkLunch.sh
	;;
stop)
	sh /oem/usr/bin/RkLunch-stop.sh
	;;
*)
	exit 1
	;;
esac
