#!/bin/sh
case "$1" in
    start)
        modprobe cfg80211
        insmod /lib/modules/$(uname -r)/extra/8812eu.ko
        wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
        udhcpc -i wlan0
        ;;
    stop)
        killall wpa_supplicant
        ip link set wlan0 down
        ;;
esac
